#ifndef _pqTableTo3DPanel_h
#define _pqTableTo3DPanel_h

#include "pqAutoGeneratedObjectPanel.h"

class pqTableTo3DPanel: public pqAutoGeneratedObjectPanel
{
Q_OBJECT
  typedef pqAutoGeneratedObjectPanel Superclass;
public:
  // Constructor
  pqTableTo3DPanel(pqProxy* proxy, QWidget* p);

  /// Destructor
  ~pqTableTo3DPanel();

protected slots:
  void onScaleModeChanged(bool checked);
  void onPrsTypeChanged(const QString& type);

};

#endif
