SET(COMPONENT_NAME PARAVIS)

INCLUDE(tests.set)

FOREACH(tfile ${TEST_NAMES})
  SET(TEST_NAME ${COMPONENT_NAME}_INTEGRATION_${tfile})
  ADD_TEST(${TEST_NAME} $ENV{ROOT_SALOME_INSTALL}/salome -m PARAVIS)
  SET_TESTS_PROPERTIES(${TEST_NAME} PROPERTIES ENVIRONMENT "PARAVIEW_OPTIONS=--test-script=${CMAKE_CURRENT_LIST_DIR}/${tfile}.xml;PARAVIEW_DATA_ROOT=${CMAKE_CURRENT_LIST_DIR};VTK_TESTING_IMAGE_COMPARE_METHOD=TIGHT_VALID")
  SET_TESTS_PROPERTIES(${TEST_NAME} PROPERTIES FAIL_REGULAR_EXPRESSION "(Failed Image Test)|(ImageNotFound)")
ENDFOREACH()
